apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: little-link-template
  title: little-link-template Title
  description: Create your little link template
  tags:
    - recommended
    - html
spec:
  owner: cenz.wong@ekimetrics.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - linkedin_url
        - email_url
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        linkedin_url:
          title: Your Linkedin URL
          type: string
          description: Your Linkedin URL; https://www.linkedin.com/in/xxxxxx
        email_url:
          title: Your Email
          type: string
          description: Your Mail URL; peter@example.com          
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: '{{ parameters.component_id }}'
          description: '{{ parameters.description }}'
          linkedin_url: '{{ parameters.linkedin_url }}'
          email_url: '{{ parameters.email_url }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          owner: '{{ parameters.owner }}'

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.component_id }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
